services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - /app
    depends_on:
      - db
      - rabbitmq
    environment:
      DB_URL: ${DB_URL}
      STORE_URL: ${STORE_URL}
    command: >
      bash -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    ports:
      - "8000:8000"

  db:
    image:
      postgres:17
    container_name: hotelroombooking-db-1
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image:
      rabbitmq:3-management
    container_name: hotelroombooking-rabbitmq-1
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${VHOST}

volumes:
  db_data:
# создаю общую сеть чтобы контейнеры могли взаимодействовать между собой.
networks:
  my_network:
    driver: bridge